import { Track, UriObject, PlayModeEnum, SonosState, ZoneAttributes, ZoneInfo, SearchMusicResult, SonosTopology, SonosSearchType } from "./sonos.model";
export declare class Sonos {
    private TRANSPORT_ENDPOINT;
    private RENDERING_ENDPOINT;
    private DEVICE_ENDPOINT;
    private host;
    private port;
    private options;
    constructor(host: string, port?: number, options?: {});
    request: (endpoint: any, action: any, body: any, responseTag: any) => Promise<any>;
    currentTrack: () => Promise<Track>;
    getVolume: () => Promise<number>;
    getMuted: () => Promise<boolean>;
    play: (uri?: string | UriObject) => Promise<boolean>;
    stop: () => Promise<boolean>;
    pause: () => Promise<boolean>;
    flush: () => Promise<any>;
    becomeCoordinatorOfStandaloneGroup: () => Promise<boolean>;
    seek: (seconds: number) => Promise<boolean>;
    next: () => Promise<boolean>;
    previous: () => Promise<boolean>;
    setName: (name: any) => Promise<any>;
    setPlayMode: (playmode: PlayModeEnum) => Promise<any>;
    setVolume: (volume: number) => Promise<any>;
    setMuted: (muted: boolean) => Promise<any>;
    selectTrack: (trackNr?: number) => Promise<boolean>;
    selectQueue: () => Promise<boolean>;
    queue: (uri: string | UriObject, positionInQueue?: number) => Promise<any>;
    getCurrentState: () => Promise<SonosState>;
    getZoneInfo: () => Promise<ZoneInfo>;
    getZoneAttrs: () => Promise<ZoneAttributes>;
    getLEDState: () => Promise<boolean>;
    setLEDState: (setStateOn: boolean) => Promise<void>;
    getTopology: () => Promise<SonosTopology>;
    deviceDescription: () => Promise<any>;
    getMusicLibrary: (searchType: SonosSearchType, startIndex?: number, pageSize?: number) => Promise<SearchMusicResult>;
    searchMusicLibrary: (searchType: SonosSearchType, searchTerm: string, startIndex?: number, pageSize?: number) => Promise<SearchMusicResult>;
    getFavoritesRadioStations: (startIndex?: number, pageSize?: number) => Promise<SearchMusicResult>;
    getFavoritesRadioShows: (startIndex?: number, pageSize?: number) => Promise<SearchMusicResult>;
    getFavoritesRadio: (favoriteRadioType: any, startIndex?: number, pageSize?: number) => Promise<SearchMusicResult>;
    getQueue: () => Promise<SearchMusicResult>;
    playTuneinRadio: (stationId: any, stationTitle: any) => Promise<boolean>;
    addSpotify: (trackId: any) => Promise<any>;
    playSpotifyRadio: (artistId: any, artistName: any) => Promise<boolean>;
    addSpotifyQueue: (trackId: any) => Promise<any>;
    private executeTransportRequest;
    private executeRequest;
    private contentSearch;
    private parseDIDL;
    private withinEnvelope;
    private htmlEntities;
    private optionsFromSpotifyUri;
}
